mysite/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns=[
    path('', views.cart_detail,name='cart_detail'),
    path('cart/add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('buy/', views.cart_buy, name='cart_buy'),  # Renamed to be more specific
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/shop/urls.py
from django.urls import path
from . import views
from .views import Search

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about),
    path('item/<int:item_id>', views.detail, name='detail'),
    path('just/', views.just, name='just'),
    path('men/', views.index_men, name='men'),
    path('men/item/<int:item_id>', views.detail, name='item_detail'),
    path('women/', views.index_women, name='women'),
    path('women/item/<int:item_id>', views.detail, name='item_detail'),
    path('PERFUMES_AND_BODY_SKIN_CARE_PRODUCTS/', views.index_PERFUMES_AND_BODY_SKIN_CARE_PRODUCTS, name='PERFUMES_AND_BODY_SKIN_CARE_PRODUCTS'),
    path('PERFUMES_AND_BODY_SKIN_CARE_PRODUCTS/item/<int:item_id>/', views.detail, name='item_detail'),
    path('search/',Search.as_view(),name='search'),
    path('search/item/<int:item_id>/',views.detail,name='item_detail'),

]

mysite/cart/models.py
from django.db import models

# Create your models here.

mysite/shop/models.py
from django.db import models
from django.urls import reverse
from django import forms


# Create your models here.
class Shop(models.Model):
    name = models.CharField(verbose_name='Название товара', max_length=60)
    price = models.IntegerField(verbose_name='Цена товара ', )
    photo_path = models.ImageField(verbose_name='Картинка ', upload_to="photo/%Y/%M/%D/",
                                   default='2144250001_2_1_16.png')
    photo_path1 = models.ImageField(verbose_name='Картинка ', upload_to="photo/%Y/%M/%D/",
                                    default='2144250001_2_1_16.png')
    photo_path2 = models.ImageField(verbose_name='Картинка ', upload_to="photo/%Y/%M/%D/",
                                    default='2144250001_2_1_16.png')
    photo_path3 = models.ImageField(verbose_name='Картинка ', upload_to="photo/%Y/%M/%D/",
                                    default='2144250001_2_1_16.png')
    description = models.TextField(verbose_name='Описание', default='')
    description1 = models.TextField(verbose_name='Описание', default='')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория', null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товары',
        verbose_name = 'Товары',


class Category(models.Model):
    name = models.CharField(verbose_name='Категория', max_length=60, db_index=True)

    def __str__(self):
        return self.name


# class Order(models.Model):
#     name = models.CharField(verbose_name='Название товара', max_length=60)
#     price = models.IntegerField(verbose_name='Цена')
#     customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
#     order_date = models.DateTimeField(auto_now_add=True)
#     quantity = models.PositiveIntegerField()

mysite/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(
        widget=forms.TextInput(attrs={'min': '1', 'value': '1'}),
        required=False,
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mysite/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .cart import Cart
from .forms import CartAddProductForm
from shop.models import Shop
from django.views.decorators.http import require_POST
from cloudipsp import Api, Checkout
from django.http import HttpResponseBadRequest


def cart_buy(request):
    cart = Cart(request)
    total = int(cart.get_total_price())
    api = Api(merchant_id=1396424,
              secret_key='test')
    checkout = Checkout(api=api)
    data = {
        "currency": "KZT",
        "amount": str(total)+'00'
    }
    url = checkout.url(data).get('checkout_url')
    return redirect(url)


@require_POST

def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Shop, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        try:
            cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
            return redirect('cart:cart_detail')
        except Exception as e:
            print(f"Error adding product to cart: {e}")
            return HttpResponseBadRequest("Error adding product to cart")
    else:
        print(form.errors)
        return HttpResponseBadRequest("Invalid form data")

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Shop, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

mysite/shop/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.http import require_POST

from cart.cart import Cart
from .models import *
from cart.forms import CartAddProductForm
from django.http import HttpResponse
from .models import Shop
from django.db.models import Q
from django.views.generic import ListView
from django.shortcuts import get_object_or_404, render


def index(request):
    items = Shop.objects.all().order_by('price')
    return render(request, 'shop/index.html', {'items': items})


def index_men(request):
    items = Shop.objects.filter(category=6).order_by('price')

    return render(request, 'shop/index.html', {'items': items})


def index_PERFUMES_AND_BODY_SKIN_CARE_PRODUCTS(request):
    items = Shop.objects.filter(category=7).order_by('price')

    return render(request, 'shop/index.html', {'items': items})


def index_women(request):
    items = Shop.objects.filter(category=5).order_by('price')

    return render(request, 'shop/index.html', {'items': items})


def about(request):
    return HttpResponse(request, 'shop/about.html')


def detail(request, item_id):
    try:
        item = Shop.objects.get(id=item_id)
        cart_product_form = CartAddProductForm()
    except Shop.DoesNotExist:
        # Обработка случая, когда товар с заданным item_id не найден
        return HttpResponse("Товар не найден")

    return render(request, 'shop/detail.html', {'item': item, 'cart_product_form': cart_product_form})


def just(request):
    # Ваша логика обработки запроса
    return render(request, 'Shop/my_template.html')


class Search(ListView):
    template_name = 'shop/index.html'
    context_object_name = 'items'  # Change context_object_name for clarity

    def get_queryset(self):
        search_query = self.request.GET.get('q', '')  # Use 'q' as the parameter name
        return Shop.objects.filter(name__icontains=search_query)

mysite/cart/templates/cart/detail.html
{%extends 'shop/base.html'%}
{% load static %}

{%block content%}

<h1>Корзина покупок</h1>

<table class="container">
    <thead>



        <th> <button type="button" class="btn btn-primary btn-sm">Картинка</button></th>
        <th> <button type="button" class="btn btn-primary btn-sm">товар</button></th>
        <th> <button type="button" class="btn btn-primary btn-sm">Обновить </button></th>
        <th> <button type="button" class="btn btn-primary btn-sm">Удалить</button></th>
        <th> <button type="button" class="btn btn-primary btn-sm">Кол-во</button></th>
        <th> <button type="button" class="btn btn-primary btn-sm">Цена </button></th>
        <th> <button type="button" class="btn btn-primary btn-sm">Общая стоимость</button></th>

    
    </thead>
    <tbody>
    {% for item in cart %}
        {% with product=item.product%}
        <tr>
            <td>
                <a href="{{product.get_absolute_url}}">
                    <img src="/media/{{product.photo_path}}" height="20%"  width="30%" style="margin: 30 px">

                </a>
            </td>
            <td>
                {{product.name}}
            </td>
            <td>
                <form action= "{% url 'cart:cart_add' product.id %}" method="post"  >
                    {{item.update_quantity_form.quantity}}
                    {{item.update_quantity_form.update}}
                    <input type="submit"  class="btn btn-sm btn-outline-secondary" value="Обновить">
                    {% csrf_token %}
                </form>
            </td>
            <td>
                <a href="{% url 'cart:cart_remove' product.id %}"><div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary">Удалить</a></button>
            </td>
            <td>
                {{item.quantity}}
            </td>
            <td class="num">
                {{item.price}} Тг
            </td>
            <td class="num">
                {{item.total_price}} Тг
            </td>
        </tr>
        {%endwith%}
    {%endfor%}
    <tr class="total">
        <td colspan="40"></td>
        <td>Всего:</td>
        <td class="sum">{{cart.get_total_price}} Тг</td>
    </tr>
    </tbody>
</table>

<p class="text-right">
    <a href="{% url 'shop:index' %}"><button type="button" class="btn btn-primary">Продолжить покупки</button>
    <a href="{% url 'cart:cart_buy' %}"><button type="button" class="btn btn-primary">Оформить заказ</button></a>

</p>

{%endblock%}

mysite/shop/templates/shop/base.html
{%load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/lux/bootstrap.min.css" integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

{%block head%} {%endblock%}

  </head>
  <body>

    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (dark)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-items d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-items d-flex align-items-center active" data-bs-theme-value="dark" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-items d-flex align-items-center" data-bs-theme-value="auto" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Massimo dutti</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="/">Home <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
  <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146ZM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5Z"/>
</svg>
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/cart/">Cart <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
</svg></a>
        </li>
        <li class="nav-item">
 <a class="nav-link" href="#scroll-target">Contacts <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tablet" viewBox="0 0 16 16">
  <path d="M12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z"/>
  <path d="M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
</svg></a>
        </li>
            <li class="nav-item">
              <a class="nav-link" href="/just/">About</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Category</a>
                <div class="dropdown-menu">
                <a class="dropdown-item" href="/men/">Men</a>
                <a class="dropdown-item" href="/women/">Women</a>
                <a class="dropdown-item" href="/PERFUMES_AND_BODY_SKIN_CARE_PRODUCTS/">PERFUMES AND BODY SKIN CARE PRODUCTS</a>
                <div class="dropdown-divider"></div>
                </div>
            </li>
      </ul>
<form class="d-flex" action="{% url 'shop:search' %}" method="get">
    <input class="form-control me-sm-2" type="text" name="q" placeholder="search" >
    <button class ="btn btn-secondary my-2 my-sm-0" type="submit" >Search</button>

</form>

    </div>
  </div>
</nav>

      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
{%block content%}

{%endblock%}


</main>

<footer class="text-body-secondary py-5">
  <div class="container">
        <p class="mb-1">Связаться с нами </p>
        <a href="https://www.instagram.com/bekkkkkontai/">
        <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
          <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
        </svg>
         </a>
        <a href="https://github.com/bekhubindustries">
          <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
            </svg>
          </a>
          <a href="https://mail.google.com/mail/u/0/#all?compose=DmwnWrRpdCrdGStXxrbMqcdnSSxDZpdXfRfnVqFlpdssxVcVCtbPlgntSKCTlBJnpnVGfrVrbJcQ">
           <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-envelope-at-fill" viewBox="0 0 16 16">
              <path d="M2 2A2 2 0 0 0 .05 3.555L8 8.414l7.95-4.859A2 2 0 0 0 14 2H2Zm-2 9.8V4.698l5.803 3.546L0 11.801Zm6.761-2.97-6.57 4.026A2 2 0 0 0 2 14h6.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586l-1.239-.757ZM16 9.671V4.697l-5.803 3.546.338.208A4.482 4.482 0 0 1 12.5 8c1.414 0 2.675.652 3.5 1.671Z"/>
              <path d="M15.834 12.244c0 1.168-.577 2.025-1.587 2.025-.503 0-1.002-.228-1.12-.648h-.043c-.118.416-.543.643-1.015.643-.77 0-1.259-.542-1.259-1.434v-.529c0-.844.481-1.4 1.26-1.4.585 0 .87.333.953.63h.03v-.568h.905v2.19c0 .272.18.42.411.42.315 0 .639-.415.639-1.39v-.118c0-1.277-.95-2.326-2.484-2.326h-.04c-1.582 0-2.64 1.067-2.64 2.724v.157c0 1.867 1.237 2.654 2.57 2.654h.045c.507 0 .935-.07 1.18-.18v.731c-.219.1-.643.175-1.237.175h-.044C10.438 16 9 14.82 9 12.646v-.214C9 10.36 10.421 9 12.485 9h.035c2.12 0 3.314 1.43 3.314 3.034v.21Zm-4.04.21v.227c0 .586.227.8.581.8.31 0 .564-.17.564-.743v-.367c0-.516-.275-.708-.572-.708-.346 0-.573.245-.573.791Z"/>
            </svg>
      </a>
  </div>
</footer>



</body></html>
    <div id="scroll-target"></div>